# Writng Syntax

In [ ]:
import pandas as pd
df = pd.DataFrame()
df.head()

Empty DataFrame
Columns: []
Index: []

# Add data

In [ ]:
dict1 = {'name':['a','b','c','e'],
         'age':[24,25,42,99]}
df = pd.DataFrame(dict1)
df.head()

  name  age
0    a   24
1    b   25
2    c   42
3    e   99

# Add new column

In [ ]:
df['birthday'] = [14,18,30,1]
df.head()

  name  age  birthday
0    a   24        14
1    b   25        18
2    c   42        30
3    e   99         1

# Add new row

In [ ]:
import pandas as pd
dict2 = {'name':['d'],
         'age':[22]}
df_new1 = pd.DataFrame(dict2)
print(df_new1.head())
df_new2 = pd.concat([df,df_new1])
df_new2

  name  age
0    d   22

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
2    c   42      30.0
3    e   99       1.0
0    d   22       NaN

In [ ]:
# datatype of NaN is float
type(df_new2['birthday'].values[3])

numpy.float64

# Get info about all column

In [ ]:
df_new2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 0
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      object
 1   age       5 non-null      int64
 2   birthday  4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

# Fetch a particular row

In [ ]:
import pandas as pd
df_new2[df_new2['age']==42]

  name  age  birthday
2    c   42      30.0

In [ ]:
df_new2[(df_new2['age']==42) & (df_new2['birthday']==30)]

  name  age  birthday
2    c   42      30.0

In [ ]:
df_new2[(df_new2['age']==42) | (df_new2['birthday']==14)]

  name  age  birthday
0    a   24      14.0
2    c   42      30.0

# Reset indexing

In [ ]:
df_2 = df_new2.reset_index()

# Drop column

In [ ]:
df_new3 = df_2.drop(['index'],axis=1)
df_new3

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
2    c   42      30.0
3    e   99       1.0
4    d   22       NaN

# Drop row

In [ ]:
df_new4 = df_new3.drop([2],axis=0)
df_new4

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
3    e   99       1.0
4    d   22       NaN

# Drop rows that contains NaN value

In [ ]:
# data cleaning
df_new4.dropna()

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
3    e   99       1.0

In [ ]:
df_new4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4 non-null      object
 1   age       4 non-null      int64
 2   birthday  3 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 128.0+ bytes

# Replace NaN values with values

In [ ]:
df_new5 = df_new3.fillna(0)
df_new5

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
2    c   42      30.0
3    e   99       1.0
4    d   22       0.0

# Change a column's data type

In [ ]:
df_new5 = df_new5['birthday'].astype(int)

In [ ]:
df_new5

0    14
1    18
2    30
3     1
4     0
Name: birthday, dtype: int32

In [ ]:
df_new4

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
3    e   99       1.0
4    d   22       NaN

In [ ]:
df_new4.fillna(1)

  name  age  birthday
0    a   24      14.0
1    b   25      18.0
3    e   99       1.0
4    d   22       1.0

In [ ]:
df_new4['birthday'] = df_new4['birthday'].astype(int)
df_new4

  name  age  birthday
0    a   24        14
1    b   25        99
3    e   99        16
4    d   22        21

In [ ]:
df_new4.describe()

            age   birthday
count   4.00000   3.000000
mean   42.50000  11.000000
std    37.68731   8.888194
min    22.00000   1.000000
25%    23.50000   7.500000
50%    24.50000  14.000000
75%    43.50000  16.000000
max    99.00000  18.000000

# Data Manipulation

# Loc / locate

In [ ]:
df_new4.loc[[4],['birthday']] = 21
df_new4

  name  age  birthday
0    a   24        14
1    b   25        99
3    e   99        16
4    d   22        21

# iloc / index of location

In [ ]:
df_new4.iloc[1,2]= 99

   index name  age  birthday
0      0    a   24        14
1      1    b   25        99
2      3    e   99        16
3      4    d   22        21

# Replace a particular value

In [ ]:
df_new4['birthday'] = df_new4['birthday'].replace(99,30)

In [ ]:
df_new4

  name  age  birthday
0    a   24        14
1    b   25        30
3    e   99        16
4    d   22        21

# save in a csv file

In [ ]:
df_new4.to_csv('demo_save.csv')

# Read that file

In [ ]:
df_read_new4 = pd.read_csv('demo_save.csv')
df_read_new4 = df_read_new4.drop(['Unnamed: 0'],axis=1)
df_read_new4

  name  age  birthday
0    a   24        14
1    b   25        30
2    e   99        16
3    d   22        21

# indexing & slicing using loc & iloc

In [ ]:
df_new4 = df_new4.reset_index()
df_new4.loc[[0,1,2],['age']]

   age
0   24
1   25
2   99

In [ ]:
df_new4=df_new4.drop(['index'],axis=1)
df_new4

  name  age  birthday
0    a   24        14
1    b   25        99
2    e   99        16
3    d   22        21

In [ ]:
df_new4.iloc[:2,1:2]

   age
0   24
1   25

# Merge

In [ ]:
import pandas as pd
df1=pd.DataFrame({'ID':[1,2,3,4],
                'Name':['Alice','Bob','Charlie','David']})
df2=pd.DataFrame({'ID':[3,4,5,6],
                'Age':[25,30,35,40]})
df1

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

In [ ]:
df2

   ID  Age
0   3   25
1   4   30
2   5   35
3   6   40

In [ ]:
pd.merge(df1,df2,on = 'ID')

   ID     Name  Age
0   3  Charlie   25
1   4    David   30

In [ ]:
pd.merge(df1,df2,on = 'ID', how='inner')   #by default

   ID     Name  Age
0   3  Charlie   25
1   4    David   30

In [ ]:
pd.merge(df1,df2,on = 'ID', how='outer') # combine

   ID     Name   Age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie  25.0
3   4    David  30.0
4   5      NaN  35.0
5   6      NaN  40.0

In [ ]:
pd.merge(df1,df2,on = 'ID', how='left') #prioritized left

   ID     Name   Age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie  25.0
3   4    David  30.0

In [ ]:
pd.merge(df1,df2,on = 'ID', how='right')

   ID     Name  Age
0   3  Charlie   25
1   4    David   30
2   5      NaN   35
3   6      NaN   40

# join

In [ ]:
import pandas as pd
df3=pd.DataFrame({'ID':[1,2,3],
                'Name':['A','B','C']},index=['a','b','c'])
df4=pd.DataFrame({'ID':[4,5,6],
                'Age':[30,35,40]},index=['b','c','d'])
df3

   ID Name
a   1    A
b   2    B
c   3    C

In [ ]:
df4

   ID  Age
b   4   30
c   5   35
d   6   40

In [ ]:
joined_df = df3.join(df4, how='outer')

ValueError: columns overlap but no suffix specified: Index(['ID'], dtype='object')